export const CARD_FACES = [
  "21 1.svg",
  "7star.svg",
  "8star.svg",
  "apple.svg",
  "banana.svg",
  "banana-1.svg",
  "bluecircle.svg",
  "bomb.svg",
  "buddha.svg",
  "confetti.svg",
  "constellation.svg",
  "cube.svg",
  "dandelion.svg",
  "diagonal.svg",
  "diamond.svg",
  "eye.svg",
  "fossil 1.svg",
  "four.svg",
  "frog.svg",
  "gem.svg",
  "hammer.svg",
  "horse.svg",
  "house.svg",
  "icecream.svg",
  "poison.svg",
  "lava.svg",
  "lightbulb.svg",
  "linedown.svg",
  "mail.svg",
  "map.svg",
  "mask.svg",
  "matchstick.svg",
  "medical.svg",
  "milk.svg",
  "noodle.svg",
  "peanut.svg",
  "pentagon.svg",
  "piechart.svg",
  "pills.svg",
  "pins.svg",
  "plug.svg",
  "popsicle.svg",
  "power.svg",
  "rainbow.svg",
  "reyna.svg",
  "rook.svg",
  "satellite.svg",
  "sewing.svg",
  "sharpener.svg",
  "sign.svg",
  "slither.svg",
  "sock.svg",
  "spade.svg",
  "spinner.svg",
  "steam.svg",
  "strips.svg",
  "sun.svg",
  "sunset.svg",
  "target.svg",
  "threaded.svg",
  "toggle.svg",
  "tree.svg",
  "triangle.svg",
  "viking.svg",
  "volcano.svg",
  "water.svg",
  "watermelon.svg",
  "wave.svg",
  "wavybands.svg",
  "wrench.svg",
] as const;

export type CardFace = (typeof CARD_FACES)[number];

export function pickRandomCardFace(): CardFace {
  return CARD_FACES[Math.floor(Math.random() * CARD_FACES.length)];
}

export function resolveCardFaceSrc(src: string) {
  if (src.startsWith("/")) return src;
  return `/cards/faces/${encodeURIComponent(src).replace(/%2F/g, "/")}`;
}

export const CARD_BACK_SRC = "/cards/backs/back.svg";
